MACHINEOVERRIDES =. "hailo10-m2:"

require include/hailo15-base.inc
require include/hailo-accelerator-base.inc

UBOOT_MACHINE = "hailo10_m2_defconfig"

UBOOT_DTBS = "hailo10-m2-8gb-2280.dtb hailo10-m2-8gb-2242.dtb hailo10-m2-4gb.dtb"

