require include/hailo10h2-base.inc
require include/veloce.inc

SCU_FW_MACHINE = "hailo10h2_veloce"
SCU_BL_MACHINE = "hailo10h2_veloce"
RECOVERY_FW_MACHINE = "hailo10h2_veloce"

UBOOT_MACHINE = "hailo10h2_veloce_defconfig"
