require include/hailo10-base.inc
require include/hailo15-base.inc
require include/hailo-accelerator-base.inc

UBOOT_MACHINE = "hailo10_usb_dongle_defconfig"

# Default linux kernel load and entry addresses are configured in hailo1x-base.inc to
# - load: 0x80c00000
# - entry: 0x80c00000
# SPL's FIT loader uses load and entry addresses as source and destination of decompression.
# So to avoid inplace decommresion, we set load address to 0x88000000, otherwise gzip decompression fails:
# - Error: inflate() returned -5 (Z_BUF_ERROR)
UBOOT_LOADADDRESS="0x88000000"
# Note, default FIT_KERNEL_COMP_ALG = "gzip"
MACHINE_FEATURES += "falcon_mode"