require include/hailo12l-base.inc
require include/veloce.inc

SCU_FW_MACHINE = "hailo12l_veloce"
SCU_BL_MACHINE = "hailo12l_veloce"
RECOVERY_FW_MACHINE = "hailo12l_veloce"

UBOOT_MACHINE = "hailo12l_veloce_defconfig"
