require include/hailo15l-base.inc
require include/hailo-vpu-base.inc

UBOOT_MACHINE = "hailo15l_sbc_nand_defconfig"

# Enable UBIFS only for hailo15l-sbc-nand
IMAGE_FSTYPES = "ubifs"

# UBIFS geometry for hailo15l-sbc-nand NAND (matches mkfs.ubifs -m 4096 -e 253952 -c 2165)
MKUBIFS_ARGS = "-m 4096 -e 253952 -c 2200"
UBINIZE_ARGS = "-m 4096 -p 256KiB -s 4096"
