MACHINEOVERRIDES =. "hailo10-m2:"

require include/hailo10-base.inc
require include/hailo15-base.inc
require include/hailo-accelerator-base.inc

UBOOT_MACHINE = "hailo10_m2_defconfig"

UBOOT_DTBS = " \
    hailo10-board-sku-0.dtb \
    hailo10-board-sku-1.dtb \
    hailo10-board-sku-3.dtb \
    hailo10-board-sku-4.dtb \
    hailo10-board-sku-5.dtb \
    hailo10-board-sku-6.dtb \
"

FIT_KERNEL_COMP_ALG="none"

MACHINE_FEATURES += "falcon_mode"
