HAILO_PACKAGE_FEED_URIS ?= ""
HAILO_PACKAGE_FEED_BASE_PATHS ?= ""
HAILO_PACKAGE_FEED_ARCHS ?= ""

# Set the base URI where the package feeds are hosted
PACKAGE_FEED_URIS = "${HAILO_PACKAGE_FEED_URIS}"

# Define the relative paths to the feeds for each architecture
PACKAGE_FEED_BASE_PATHS = "${HAILO_PACKAGE_FEED_BASE_PATHS}"

# Specify the architectures for which the feeds are relevant
PACKAGE_FEED_ARCHS = "${HAILO_PACKAGE_FEED_ARCHS}"
