[Journal]
#   Specifies that journal logs are stored in volatile memory (RAM) and not persisted to disk.
Storage=volatile
#   Enables forwarding of log messages to the syslog service.
ForwardToSyslog=yes
#   Only log messages with priority 'err' (error) or higher are forwarded to syslog.
MaxLevelSyslog=err
#   Disables forwarding of log messages to the kernel log buffer (/dev/kmsg).
ForwardToKMsg=no
#   Only log messages with priority 'err' (error) or higher are forwarded to the system console.
MaxLevelConsole=err
#   Disables log compression to reduce CPU overhead
Compress=no
#   Prevents log flooding by allowing max 200 messages per 30-second window from the same source.
RateLimitInterval=30s
RateLimitBurst=200
#   Limits the maximum size of the journal log to 4MB in volatile storage.
RuntimeMaxUse=4M
#   Ensures at least 1MB of free space remains in the log storage area.
RuntimeKeepFree=1M
